var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(tools)/json-diff/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13sx6qk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0n0ibz8.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sqo0ut._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p3qowm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04~y~ez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(tools)_layout_tsx_0jek.r4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(tools)_json-diff_page_actions_0rk~-65.js")
R.m(10154)
module.exports=R.m(10154).exports
