var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/workspace/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__06f~9a7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0svgr8x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sqo0ut._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p3qowm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04~y~ez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_workspace_layout_tsx_0qw9vy5._.js")
R.c("server/chunks/ssr/src_app_workspace_error_tsx_10m2u.0._.js")
R.c("server/chunks/ssr/src_app_workspace_loading_tsx_0t~~7_o._.js")
R.c("server/chunks/ssr/_next-internal_server_app_workspace_page_actions_0358byy.js")
R.m(25450)
module.exports=R.m(25450).exports
