var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(tools)/mock-json-generator/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03vz0bo._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_07l_l7m.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sqo0ut._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p3qowm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__04~y~ez._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_(tools)_layout_tsx_0jek.r4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(tools)_mock-json-generator_page_actions_04i30z0.js")
R.m(35098)
module.exports=R.m(35098).exports
